# syntax of the user configuration
syntax_version: 0.1

# Taken from the default apt installation target
# /opt/ros/<ros_distro>
ros_distro: groovy

ws:
  rosbuild:
    type: rosbuild
    dir: ros/rosbuild_ws
    rosinstall:
      - uri: https://raw.github.com/bwi-spring-2013/segbot/master/rosinstall/segbot.rw.rosinstall
      - uri: https://raw.github.com/piyushk/freenect_stack/master/rosinstall/freenect.rosinstall 
      - uri: https://raw.github.com/bwi-spring-2013/multi_level_map/master/rosinstall/multi_level_map.rw.rosinstall
      - svn:
          local-name: gazebo_plugins
          uri: https://code.ros.org/svn/ros-pkg/stacks/simulator_gazebo/tags/simulator_gazebo-1.7.6/gazebo_plugins/

    # the patch uri can be an absolute paths on the machine as well
    patches:
      - gazebo_plugins: http://z.cs.utexas.edu/users/piyushk/share/gazebo_plugins.kinect_depth.patch 

  catkin:
    type: catkin
    dir: ros/catkin_ws

  gazebo:
    type: generic
    dir: ros/gazebo
    bash: |
      export GAZEBO_MODEL_PATH=~/ros/gazebo/gazebo_models:${GAZEBO_MODEL_PATH}
    rosinstall:
      - hg:
          local-name: gazebo_models
          uri: https://bitbucket.org/osrf/gazebo_models
